# dependabot.yml file with

version: 2
updates:
  # Keep yarn dependencies up to date
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
      timezone: "America/New_York"
    target-branch: "master"
    labels:
      - "yarn dependencies"
    reviewers:
      - "0xlil14n"
    